version: "2"

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -k gevent -b 0.0.0.0:15000 whynot.application:app
    environment:
      - WHYNOT_SETTINGS=/usr/src/app/prd_settings.py
    ports:
      - "15000:15000"

  mongo:
    image: mongo
